// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: wareshare_test1

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, lv_pct(100));
    lv_obj_set_height(ui_TabView1, lv_pct(100));
    lv_obj_set_x(ui_TabView1, 1);
    lv_obj_set_y(ui_TabView1, 0);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_acctab = lv_tabview_add_tab(ui_TabView1, "Ivme Olcer");

    ui_Panel1 = lv_obj_create(ui_acctab);
    lv_obj_set_height(ui_Panel1, 87);
    lv_obj_set_width(ui_Panel1, lv_pct(60));
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -131);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_acctab);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -149);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Ivme y");

    ui_Label2 = lv_label_create(ui_acctab);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -150);
    lv_obj_set_y(ui_Label2, -150);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Ivme x");

    ui_Label3 = lv_label_create(ui_acctab);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 150);
    lv_obj_set_y(ui_Label3, -149);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Ivme z");

    ui_bartab = lv_tabview_add_tab(ui_TabView1, "Basinc | Sicaklik");

    ui_Keyboard1 = lv_keyboard_create(ui_bartab);
    lv_obj_set_width(ui_Keyboard1, lv_pct(80));
    lv_obj_set_height(ui_Keyboard1, lv_pct(60));
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, lv_pct(25));
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_motorcontrol = lv_tabview_add_tab(ui_TabView1, "Motor");

    ui_Slider1 = lv_slider_create(ui_motorcontrol);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 200);
    lv_obj_set_height(ui_Slider1, 20);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Label4 = lv_label_create(ui_motorcontrol);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -36);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Motor Signal");

    ui_Label5 = lv_label_create(ui_motorcontrol);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 39);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "0");

}
